"use client";
import Link from"next/link";import{ArrowRight,Play,ChevronRight,Headphones,LampDesk,Watch,Sofa,Sparkles,Clock3,Truck,ShieldCheck,RotateCcw}from"lucide-react";import ProductGrid from"../components/ProductGrid";
const cats=[["Audio",Headphones,"Violet"],["Workspace",LampDesk,"Ice"],["Living",Sofa,"Coral"],["Wearables",Watch,"Lime"]];
export default function Page(){return <main>
<section className="hero"><div className="copy"><div className="eyebrow">RYZE / FUTURE ESSENTIALS</div><h1>DISCOVER<br/><i>WHAT'S NEXT.</i></h1><p>Original objects for your sound, space and everyday. Curated for people moving forward.</p><div className="heroActions"><Link className="primary" href="/browse">Explore the drop <ArrowRight size={18}/></Link><button className="round"><Play size={17}/></button></div><div className="heroTrust"><span><Truck/>Fast delivery preview</span><span><ShieldCheck/>Protected checkout</span></div></div><div className="visualStage"><div className="glow"></div><div className="headsetArt"><span className="band"></span><span className="cup l"></span><span className="cup r"></span></div><span className="floatChip fc1">AUDIO / 01</span><span className="floatChip fc2">ADAPTIVE SOUND</span><span className="floatChip fc3">RYZE SELECT</span></div></section>
<section className="ticker">NEW TECH <b>✦</b> BETTER SPACES <b>✦</b> EVERYDAY OBJECTS <b>✦</b> RYZE EXCLUSIVES</section>
<section className="benefitBar"><span><Truck/>Fast delivery</span><span><RotateCcw/>Easy returns preview</span><span><ShieldCheck/>Secure checkout</span><span><Sparkles/>Curated drops</span></section>
<section className="section"><div className="sectionHead"><div><small>01 / EXPLORE</small><h2>Browse your world.</h2></div><Link href="/browse">View all <ArrowRight size={16}/></Link></div><div className="cats">{cats.map(([n,I,c]:any)=><Link href={"/browse?category="+n} className={"cat "+c} key={n}><div className="catTop"><span>{n}</span><button><ChevronRight/></button></div><I size={60}/><small>SHOP CATEGORY</small></Link>)}</div></section>
<section className="campaign"><div className="campaignArt"><div className="speakerArt"><i></i><i></i><i></i></div></div><div><small>RYZE AUDIO / DROP 04</small><h2>Turn up<br/>your world.</h2><p>Immersive sound, sculptural forms and everyday portability.</p><Link className="primary" href="/browse">Explore Audio <ArrowRight/></Link></div></section>
<section className="dark"><div className="sectionHead"><div><small>02 / TRENDING NOW</small><h2>Things worth<br/>wanting.</h2></div><p>Selected objects that make everyday life feel a little more future.</p></div><ProductGrid/></section>
<section className="dealStrip"><div><Clock3/><small>RYZE DROP / LIMITED PREVIEW</small><h2>10% off with <b>RYZE10</b></h2></div><Link href="/browse">Shop the drop <ArrowRight/></Link></section>
<section className="scene"><div><small>03 / SHOP THE SCENE</small><h2>Build a better<br/>desk.</h2><p>A complete workspace assembled around focus, sound and light.</p><Link className="primary" href="/browse">Shop complete setup <ArrowRight size={18}/></Link></div><div className="deskArt"><div className="monitor"><i></i></div><div className="lampArt"></div><div className="keyboardArt"></div><div className="deskHeadphones"></div><div className="tableEdge"></div></div></section>
<section className="finder"><div><small>NOT SURE WHAT FITS?</small><h2>Meet the RYZE Finder.</h2><p>Pick a category and budget. We’ll narrow the collection for you.</p></div><Link className="primary" href="/search">Find my product <ArrowRight/></Link></section>
</main>}