"use client";
import {Search,MapPin,Heart,ShoppingBag,User,Grid2X2,Home,ArrowRight,Play,ChevronRight,Headphones,LampDesk,Watch,Sofa} from "lucide-react";
const products=[["AeroPods X","₹2,499","Audio","🎧"],["Arc Light Mini","₹1,799","Workspace","💡"],["Pulse One","₹3,299","Wearables","⌚"],["Cloud Speaker","₹2,899","Living","🔊"]];
const cats=[["Audio",Headphones,"Violet"],["Workspace",LampDesk,"Ice"],["Living",Sofa,"Coral"],["Wearables",Watch,"Lime"]];
export default function Page(){return <main>
<header><b className="logo">RYZE<span>STORES</span></b><div className="search"><Search size={18}/><span>Search products, categories & more</span></div><button className="location"><MapPin size={17}/> Deliver to your location</button><nav><Heart/><User/><ShoppingBag/></nav></header>
<section className="hero"><div className="copy"><div className="eyebrow">RYZE / NEW ERA 2026</div><h1>DISCOVER<br/><i>WHAT'S NEXT.</i></h1><p>Objects for your sound, space and everyday. Curated differently.</p><div><button className="primary">Explore the drop <ArrowRight size={18}/></button><button className="round"><Play size={17}/></button></div></div><div className="orb"><div className="product">🎧</div><span className="tag t1">NEW / AUDIO</span><span className="tag t2">IMMERSIVE SOUND</span></div></section>
<section className="ticker">NEW TECH <b>✦</b> BETTER SPACES <b>✦</b> EVERYDAY OBJECTS <b>✦</b> RYZE EXCLUSIVES</section>
<section className="section"><div className="sectionHead"><div><small>01 / EXPLORE</small><h2>Browse your world.</h2></div><a>View all <ArrowRight size={16}/></a></div><div className="cats">{cats.map(([n,I,c]:any)=><article className={"cat "+c} key={n}><div className="catTop"><span>{n}</span><button><ChevronRight/></button></div><I size={60}/><small>SHOP CATEGORY</small></article>)}</div></section>
<section className="dark"><div className="sectionHead"><div><small>02 / TRENDING NOW</small><h2>Things worth<br/>wanting.</h2></div><p>Selected objects that make everyday life feel a little more future.</p></div><div className="products">{products.map((p,i)=><article className="card" key={p[0]}><button className="heart"><Heart/></button><div className="pimg">{p[3]}</div><small>{p[2]}</small><h3>{p[0]}</h3><div className="price"><b>{p[1]}</b><button><ShoppingBag size={17}/> Add</button></div></article>)}</div></section>
<section className="scene"><div><small>03 / SHOP THE SCENE</small><h2>Build a better<br/>desk.</h2><p>One setup. Five objects. Designed to work together.</p><button className="primary">Shop complete setup <ArrowRight size={18}/></button></div><div className="desk"><span>🖥️</span><span>⌨️</span><span>🎧</span><span>💡</span></div></section>
<div className="mobileNav"><button><Home/><span>Home</span></button><button><Grid2X2/><span>Browse</span></button><button><ShoppingBag/><span>Cart</span></button><button><User/><span>Profile</span></button></div>
</main>}